<a href="https://colab.research.google.com/github/FatiBuuloloo/E-commerce_Shopper_Behavior_Mining_PrefixSpan_-_Association-mini_project-012/blob/main/notebooks/sequence_event2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
from google.colab import drive

drive.mount('/content/drive')
os.environ['KAGGLE_CONFIG_DIR'] = "/content/drive/MyDrive/Kaggle"
os.chdir("/content")
print("Path:", os.getcwd())

Mounted at /content/drive
Path: /content

In [ ]:
!kaggle datasets download -d mkechinov/ecommerce-behavior-data-from-multi-category-store

Dataset URL: https://www.kaggle.com/datasets/mkechinov/ecommerce-behavior-data-from-multi-category-store
License(s): copyright-authors
Downloading ecommerce-behavior-data-from-multi-category-store.zip to /content
100% 4.29G/4.29G [00:41<00:00, 112MB/s]

In [ ]:
!unzip -q /content/*.zip -d /content/
!rm /content/*.zip
!ls -lh /content/*.csv

-rw-r--r-- 1 root root 8.4G Dec  9  2019 /content/2019-Nov.csv
-rw-r--r-- 1 root root 5.3G Dec  9  2019 /content/2019-Oct.csv

In [ ]:
import pandas as pd
import json
from google.colab import files

In [ ]:
data1 = pd.read_csv('/content/2019-Oct.csv')
#data2 = pd.read_csv('/content/2019-Nov.csv')
data1.columns

Index(['event_time', 'event_type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='object')

In [ ]:
data1.shape

(42448764, 9)

In [ ]:
(data1.isna().sum() / len(data1)) * 100

event_time        0.000000
event_type        0.000000
product_id        0.000000
category_id       0.000000
category_code    31.839818
brand            14.410502
price             0.000000
user_id           0.000000
user_session      0.000005
dtype: float64

In [ ]:
data1["event_time"] = pd.to_datetime(data1["event_time"]).dt.tz_localize(None)
data1.dropna(subset="user_session",inplace=True)

In [ ]:
print("Number of Unique Users:", data1['user_id'].nunique())
print("Number of Unique Session:", data1['user_session'].nunique())
print("Number of Event:\n", data1['event_type'].value_counts())

Number of Unique Users: 3022290
Number of Unique Session: 9244421
Number of Event:
 event_type
view        40779399
cart          926514
purchase      742849
Name: count, dtype: int64

In [ ]:
data1 = data1.sort_values(by=["user_id","event_time"]).reset_index(drop=True)
data1 = data1.iloc[22000004:,:]

In [ ]:
data1["brand"] = data1["brand"].fillna("Unknown")
data1["event_action"] = data1["event_type"]+"_"+data1["brand"]

In [ ]:
data1.head(5)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session,event_action
22000004,2019-10-26 18:27:43,view,12709556,2053013553559896355,NaN,viatti,40.16,531564317,408497ca-fafc-4dd7-8c21-c1f8e4fb67d0,view_viatti
22000005,2019-10-26 18:28:38,view,12706656,2053013553559896355,NaN,nokian,50.71,531564317,408497ca-fafc-4dd7-8c21-c1f8e4fb67d0,view_nokian
22000006,2019-10-26 18:29:17,view,12706656,2053013553559896355,NaN,nokian,50.71,531564317,408497ca-fafc-4dd7-8c21-c1f8e4fb67d0,view_nokian
22000007,2019-10-26 18:29:32,view,12714714,2053013553559896355,NaN,tunga,43.76,531564317,408497ca-fafc-4dd7-8c21-c1f8e4fb67d0,view_tunga
22000008,2019-10-26 18:30:07,view,12712660,2053013553559896355,NaN,toyo,50.19,531564317,408497ca-fafc-4dd7-8c21-c1f8e4fb67d0,view_toyo

In [ ]:
sequence_event = data1.groupby(['user_id', 'user_session'])['event_action'].apply(list).tolist()
sequence_event = list(filter(lambda x: len(x)!=1, sequence_event))

In [ ]:
with open('sequence_event2.json', 'w') as f:
    json.dump(sequence_event, f)
files.download('sequence_event2.json')